.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gIvysaurLevelUpLearnset+SizeRom
.word gVenusaurLevelUpLearnset+SizeRom
.word gCharmanderLevelUpLearnset+SizeRom
.word gCharmeleonLevelUpLearnset+SizeRom
.word gCharizardLevelUpLearnset+SizeRom
.word gSquirtleLevelUpLearnset+SizeRom
.word gWartortleLevelUpLearnset+SizeRom
.word gBlastoiseLevelUpLearnset+SizeRom
.word gCaterpieLevelUpLearnset+SizeRom
.word gMetapodLevelUpLearnset+SizeRom
.word gButterfreeLevelUpLearnset+SizeRom
.word gWeedleLevelUpLearnset+SizeRom
.word gKakunaLevelUpLearnset+SizeRom
.word gBeedrillLevelUpLearnset+SizeRom
.word gPidgeyLevelUpLearnset+SizeRom
.word gPidgeottoLevelUpLearnset+SizeRom
.word gPidgeotLevelUpLearnset+SizeRom
.word gRattataLevelUpLearnset+SizeRom
.word gRaticateLevelUpLearnset+SizeRom
.word gSpearowLevelUpLearnset+SizeRom
.word gFearowLevelUpLearnset+SizeRom
.word gEkansLevelUpLearnset+SizeRom
.word gArbokLevelUpLearnset+SizeRom
.word gPikachuLevelUpLearnset+SizeRom
.word gRaichuLevelUpLearnset+SizeRom
.word gSandshrewLevelUpLearnset+SizeRom
.word gSandslashLevelUpLearnset+SizeRom
.word gNidoranFLevelUpLearnset+SizeRom
.word gNidorinaLevelUpLearnset+SizeRom
.word gNidoqueenLevelUpLearnset+SizeRom
.word gNidoranMLevelUpLearnset+SizeRom
.word gNidorinoLevelUpLearnset+SizeRom
.word gNidokingLevelUpLearnset+SizeRom
.word gClefairyLevelUpLearnset+SizeRom
.word gClefableLevelUpLearnset+SizeRom
.word gVulpixLevelUpLearnset+SizeRom
.word gNinetalesLevelUpLearnset+SizeRom
.word gJigglypuffLevelUpLearnset+SizeRom
.word gWigglytuffLevelUpLearnset+SizeRom
.word gZubatLevelUpLearnset+SizeRom
.word gGolbatLevelUpLearnset+SizeRom
.word gOddishLevelUpLearnset+SizeRom
.word gGloomLevelUpLearnset+SizeRom
.word gVileplumeLevelUpLearnset+SizeRom
.word gParasLevelUpLearnset+SizeRom
.word gParasectLevelUpLearnset+SizeRom
.word gVenonatLevelUpLearnset+SizeRom
.word gVenomothLevelUpLearnset+SizeRom
.word gDiglettLevelUpLearnset+SizeRom
.word gDugtrioLevelUpLearnset+SizeRom
.word gMeowthLevelUpLearnset+SizeRom
.word gPersianLevelUpLearnset+SizeRom
.word gPsyduckLevelUpLearnset+SizeRom
.word gGolduckLevelUpLearnset+SizeRom
.word gMankeyLevelUpLearnset+SizeRom
.word gPrimeapeLevelUpLearnset+SizeRom
.word gGrowlitheLevelUpLearnset+SizeRom
.word gArcanineLevelUpLearnset+SizeRom
.word gPoliwagLevelUpLearnset+SizeRom
.word gPoliwhirlLevelUpLearnset+SizeRom
.word gPoliwrathLevelUpLearnset+SizeRom
.word gAbraLevelUpLearnset+SizeRom
.word gKadabraLevelUpLearnset+SizeRom
.word gAlakazamLevelUpLearnset+SizeRom
.word gMachopLevelUpLearnset+SizeRom
.word gMachokeLevelUpLearnset+SizeRom
.word gMachampLevelUpLearnset+SizeRom
.word gBellsproutLevelUpLearnset+SizeRom
.word gWeepinbellLevelUpLearnset+SizeRom
.word gVictreebelLevelUpLearnset+SizeRom
.word gTentacoolLevelUpLearnset+SizeRom
.word gTentacruelLevelUpLearnset+SizeRom
.word gGeodudeLevelUpLearnset+SizeRom
.word gGravelerLevelUpLearnset+SizeRom
.word gGolemLevelUpLearnset+SizeRom
.word gPonytaLevelUpLearnset+SizeRom
.word gRapidashLevelUpLearnset+SizeRom
.word gSlowpokeLevelUpLearnset+SizeRom
.word gSlowbroLevelUpLearnset+SizeRom
.word gMagnemiteLevelUpLearnset+SizeRom
.word gMagnetonLevelUpLearnset+SizeRom
.word gFarfetchdLevelUpLearnset+SizeRom
.word gDoduoLevelUpLearnset+SizeRom
.word gDodrioLevelUpLearnset+SizeRom
.word gSeelLevelUpLearnset+SizeRom
.word gDewgongLevelUpLearnset+SizeRom
.word gGrimerLevelUpLearnset+SizeRom
.word gMukLevelUpLearnset+SizeRom
.word gShellderLevelUpLearnset+SizeRom
.word gCloysterLevelUpLearnset+SizeRom
.word gGastlyLevelUpLearnset+SizeRom
.word gHaunterLevelUpLearnset+SizeRom
.word gGengarLevelUpLearnset+SizeRom
.word gOnixLevelUpLearnset+SizeRom
.word gDrowzeeLevelUpLearnset+SizeRom
.word gHypnoLevelUpLearnset+SizeRom
.word gKrabbyLevelUpLearnset+SizeRom
.word gKinglerLevelUpLearnset+SizeRom
.word gVoltorbLevelUpLearnset+SizeRom
.word gElectrodeLevelUpLearnset+SizeRom
.word gExeggcuteLevelUpLearnset+SizeRom
.word gExeggutorLevelUpLearnset+SizeRom
.word gCuboneLevelUpLearnset+SizeRom
.word gMarowakLevelUpLearnset+SizeRom
.word gHitmonleeLevelUpLearnset+SizeRom
.word gHitmonchanLevelUpLearnset+SizeRom
.word gLickitungLevelUpLearnset+SizeRom
.word gKoffingLevelUpLearnset+SizeRom
.word gWeezingLevelUpLearnset+SizeRom
.word gRhyhornLevelUpLearnset+SizeRom
.word gRhydonLevelUpLearnset+SizeRom
.word gChanseyLevelUpLearnset+SizeRom
.word gTangelaLevelUpLearnset+SizeRom
.word gKangaskhanLevelUpLearnset+SizeRom
.word gHorseaLevelUpLearnset+SizeRom
.word gSeadraLevelUpLearnset+SizeRom
.word gGoldeenLevelUpLearnset+SizeRom
.word gSeakingLevelUpLearnset+SizeRom
.word gStaryuLevelUpLearnset+SizeRom
.word gStarmieLevelUpLearnset+SizeRom
.word gMrmimeLevelUpLearnset+SizeRom
.word gScytherLevelUpLearnset+SizeRom
.word gJynxLevelUpLearnset+SizeRom
.word gElectabuzzLevelUpLearnset+SizeRom
.word gMagmarLevelUpLearnset+SizeRom
.word gPinsirLevelUpLearnset+SizeRom
.word gTaurosLevelUpLearnset+SizeRom
.word gMagikarpLevelUpLearnset+SizeRom
.word gGyaradosLevelUpLearnset+SizeRom
.word gLaprasLevelUpLearnset+SizeRom
.word gDittoLevelUpLearnset+SizeRom
.word gEeveeLevelUpLearnset+SizeRom
.word gVaporeonLevelUpLearnset+SizeRom
.word gJolteonLevelUpLearnset+SizeRom
.word gFlareonLevelUpLearnset+SizeRom
.word gPorygonLevelUpLearnset+SizeRom
.word gOmanyteLevelUpLearnset+SizeRom
.word gOmastarLevelUpLearnset+SizeRom
.word gKabutoLevelUpLearnset+SizeRom
.word gKabutopsLevelUpLearnset+SizeRom
.word gAerodactylLevelUpLearnset+SizeRom
.word gSnorlaxLevelUpLearnset+SizeRom
.word gArticunoLevelUpLearnset+SizeRom
.word gZapdosLevelUpLearnset+SizeRom
.word gMoltresLevelUpLearnset+SizeRom
.word gDratiniLevelUpLearnset+SizeRom
.word gDragonairLevelUpLearnset+SizeRom
.word gDragoniteLevelUpLearnset+SizeRom
.word gMewtwoLevelUpLearnset+SizeRom
.word gMewLevelUpLearnset+SizeRom
.word gChikoritaLevelUpLearnset+SizeRom
.word gBayleefLevelUpLearnset+SizeRom
.word gMeganiumLevelUpLearnset+SizeRom
.word gCyndaquilLevelUpLearnset+SizeRom
.word gQuilavaLevelUpLearnset+SizeRom
.word gTyphlosionLevelUpLearnset+SizeRom
.word gTotodileLevelUpLearnset+SizeRom
.word gCroconawLevelUpLearnset+SizeRom
.word gFeraligatrLevelUpLearnset+SizeRom
.word gSentretLevelUpLearnset+SizeRom
.word gFurretLevelUpLearnset+SizeRom
.word gHoothootLevelUpLearnset+SizeRom
.word gNoctowlLevelUpLearnset+SizeRom
.word gLedybaLevelUpLearnset+SizeRom
.word gLedianLevelUpLearnset+SizeRom
.word gSpinarakLevelUpLearnset+SizeRom
.word gAriadosLevelUpLearnset+SizeRom
.word gCrobatLevelUpLearnset+SizeRom
.word gChinchouLevelUpLearnset+SizeRom
.word gLanturnLevelUpLearnset+SizeRom
.word gPichuLevelUpLearnset+SizeRom
.word gCleffaLevelUpLearnset+SizeRom
.word gIgglybuffLevelUpLearnset+SizeRom
.word gTogepiLevelUpLearnset+SizeRom
.word gTogeticLevelUpLearnset+SizeRom
.word gNatuLevelUpLearnset+SizeRom
.word gXatuLevelUpLearnset+SizeRom
.word gMareepLevelUpLearnset+SizeRom
.word gFlaaffyLevelUpLearnset+SizeRom
.word gAmpharosLevelUpLearnset+SizeRom
.word gBellossomLevelUpLearnset+SizeRom
.word gMarillLevelUpLearnset+SizeRom
.word gAzumarillLevelUpLearnset+SizeRom
.word gSudowoodoLevelUpLearnset+SizeRom
.word gPolitoedLevelUpLearnset+SizeRom
.word gHoppipLevelUpLearnset+SizeRom
.word gSkiploomLevelUpLearnset+SizeRom
.word gJumpluffLevelUpLearnset+SizeRom
.word gAipomLevelUpLearnset+SizeRom
.word gSunkernLevelUpLearnset+SizeRom
.word gSunfloraLevelUpLearnset+SizeRom
.word gYanmaLevelUpLearnset+SizeRom
.word gWooperLevelUpLearnset+SizeRom
.word gQuagsireLevelUpLearnset+SizeRom
.word gEspeonLevelUpLearnset+SizeRom
.word gUmbreonLevelUpLearnset+SizeRom
.word gMurkrowLevelUpLearnset+SizeRom
.word gSlowkingLevelUpLearnset+SizeRom
.word gMisdreavusLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gWobbuffetLevelUpLearnset+SizeRom
.word gGirafarigLevelUpLearnset+SizeRom
.word gPinecoLevelUpLearnset+SizeRom
.word gForretressLevelUpLearnset+SizeRom
.word gDunsparceLevelUpLearnset+SizeRom
.word gGligarLevelUpLearnset+SizeRom
.word gSteelixLevelUpLearnset+SizeRom
.word gSnubbullLevelUpLearnset+SizeRom
.word gGranbullLevelUpLearnset+SizeRom
.word gQwilfishLevelUpLearnset+SizeRom
.word gScizorLevelUpLearnset+SizeRom
.word gShuckleLevelUpLearnset+SizeRom
.word gHeracrossLevelUpLearnset+SizeRom
.word gSneaselLevelUpLearnset+SizeRom
.word gTeddiursaLevelUpLearnset+SizeRom
.word gUrsaringLevelUpLearnset+SizeRom
.word gSlugmaLevelUpLearnset+SizeRom
.word gMagcargoLevelUpLearnset+SizeRom
.word gSwinubLevelUpLearnset+SizeRom
.word gPiloswineLevelUpLearnset+SizeRom
.word gCorsolaLevelUpLearnset+SizeRom
.word gRemoraidLevelUpLearnset+SizeRom
.word gOctilleryLevelUpLearnset+SizeRom
.word gDelibirdLevelUpLearnset+SizeRom
.word gMantineLevelUpLearnset+SizeRom
.word gSkarmoryLevelUpLearnset+SizeRom
.word gHoundourLevelUpLearnset+SizeRom
.word gHoundoomLevelUpLearnset+SizeRom
.word gKingdraLevelUpLearnset+SizeRom
.word gPhanpyLevelUpLearnset+SizeRom
.word gDonphanLevelUpLearnset+SizeRom
.word gPorygon2LevelUpLearnset+SizeRom
.word gStantlerLevelUpLearnset+SizeRom
.word gSmeargleLevelUpLearnset+SizeRom
.word gTyrogueLevelUpLearnset+SizeRom
.word gHitmontopLevelUpLearnset+SizeRom
.word gSmoochumLevelUpLearnset+SizeRom
.word gElekidLevelUpLearnset+SizeRom
.word gMagbyLevelUpLearnset+SizeRom
.word gMiltankLevelUpLearnset+SizeRom
.word gBlisseyLevelUpLearnset+SizeRom
.word gRaikouLevelUpLearnset+SizeRom
.word gEnteiLevelUpLearnset+SizeRom
.word gSuicuneLevelUpLearnset+SizeRom
.word gLarvitarLevelUpLearnset+SizeRom
.word gPupitarLevelUpLearnset+SizeRom
.word gTyranitarLevelUpLearnset+SizeRom
.word gLugiaLevelUpLearnset+SizeRom
.word gHoOhLevelUpLearnset+SizeRom
.word gCelebiLevelUpLearnset+SizeRom
.word gSpecies252LevelUpLearnset+SizeRom
.word gSpecies253LevelUpLearnset+SizeRom
.word gSpecies254LevelUpLearnset+SizeRom
.word gSpecies255LevelUpLearnset+SizeRom
.word gSpecies256LevelUpLearnset+SizeRom
.word gSpecies257LevelUpLearnset+SizeRom
.word gSpecies258LevelUpLearnset+SizeRom
.word gSpecies259LevelUpLearnset+SizeRom
.word gSpecies260LevelUpLearnset+SizeRom
.word gSpecies261LevelUpLearnset+SizeRom
.word gSpecies262LevelUpLearnset+SizeRom
.word gSpecies263LevelUpLearnset+SizeRom
.word gSpecies264LevelUpLearnset+SizeRom
.word gSpecies265LevelUpLearnset+SizeRom
.word gSpecies266LevelUpLearnset+SizeRom
.word gSpecies267LevelUpLearnset+SizeRom
.word gSpecies268LevelUpLearnset+SizeRom
.word gSpecies269LevelUpLearnset+SizeRom
.word gSpecies270LevelUpLearnset+SizeRom
.word gSpecies271LevelUpLearnset+SizeRom
.word gSpecies272LevelUpLearnset+SizeRom
.word gSpecies273LevelUpLearnset+SizeRom
.word gSpecies274LevelUpLearnset+SizeRom
.word gSpecies275LevelUpLearnset+SizeRom
.word gSpecies276LevelUpLearnset+SizeRom
.word gTreeckoLevelUpLearnset+SizeRom
.word gGrovyleLevelUpLearnset+SizeRom
.word gSceptileLevelUpLearnset+SizeRom
.word gTorchicLevelUpLearnset+SizeRom
.word gCombuskenLevelUpLearnset+SizeRom
.word gBlazikenLevelUpLearnset+SizeRom
.word gMudkipLevelUpLearnset+SizeRom
.word gMarshtompLevelUpLearnset+SizeRom
.word gSwampertLevelUpLearnset+SizeRom
.word gPoochyenaLevelUpLearnset+SizeRom
.word gMightyenaLevelUpLearnset+SizeRom
.word gZigzagoonLevelUpLearnset+SizeRom
.word gLinooneLevelUpLearnset+SizeRom
.word gWurmpleLevelUpLearnset+SizeRom
.word gSilcoonLevelUpLearnset+SizeRom
.word gBeautiflyLevelUpLearnset+SizeRom
.word gCascoonLevelUpLearnset+SizeRom
.word gDustoxLevelUpLearnset+SizeRom
.word gLotadLevelUpLearnset+SizeRom
.word gLombreLevelUpLearnset+SizeRom
.word gLudicoloLevelUpLearnset+SizeRom
.word gSeedotLevelUpLearnset+SizeRom
.word gNuzleafLevelUpLearnset+SizeRom
.word gShiftryLevelUpLearnset+SizeRom
.word gNincadaLevelUpLearnset+SizeRom
.word gNinjaskLevelUpLearnset+SizeRom
.word gShedinjaLevelUpLearnset+SizeRom
.word gTaillowLevelUpLearnset+SizeRom
.word gSwellowLevelUpLearnset+SizeRom
.word gShroomishLevelUpLearnset+SizeRom
.word gBreloomLevelUpLearnset+SizeRom
.word gSpindaLevelUpLearnset+SizeRom
.word gWingullLevelUpLearnset+SizeRom
.word gPelipperLevelUpLearnset+SizeRom
.word gSurskitLevelUpLearnset+SizeRom
.word gMasquerainLevelUpLearnset+SizeRom
.word gWailmerLevelUpLearnset+SizeRom
.word gWailordLevelUpLearnset+SizeRom
.word gSkittyLevelUpLearnset+SizeRom
.word gDelcattyLevelUpLearnset+SizeRom
.word gKecleonLevelUpLearnset+SizeRom
.word gBaltoyLevelUpLearnset+SizeRom
.word gClaydolLevelUpLearnset+SizeRom
.word gNosepassLevelUpLearnset+SizeRom
.word gTorkoalLevelUpLearnset+SizeRom
.word gSableyeLevelUpLearnset+SizeRom
.word gBarboachLevelUpLearnset+SizeRom
.word gWhiscashLevelUpLearnset+SizeRom
.word gLuvdiscLevelUpLearnset+SizeRom
.word gCorphishLevelUpLearnset+SizeRom
.word gCrawdauntLevelUpLearnset+SizeRom
.word gFeebasLevelUpLearnset+SizeRom
.word gMiloticLevelUpLearnset+SizeRom
.word gCarvanhaLevelUpLearnset+SizeRom
.word gSharpedoLevelUpLearnset+SizeRom
.word gTrapinchLevelUpLearnset+SizeRom
.word gVibravaLevelUpLearnset+SizeRom
.word gFlygonLevelUpLearnset+SizeRom
.word gMakuhitaLevelUpLearnset+SizeRom
.word gHariyamaLevelUpLearnset+SizeRom
.word gElectrikeLevelUpLearnset+SizeRom
.word gManectricLevelUpLearnset+SizeRom
.word gNumelLevelUpLearnset+SizeRom
.word gCameruptLevelUpLearnset+SizeRom
.word gSphealLevelUpLearnset+SizeRom
.word gSealeoLevelUpLearnset+SizeRom
.word gWalreinLevelUpLearnset+SizeRom
.word gCacneaLevelUpLearnset+SizeRom
.word gCacturneLevelUpLearnset+SizeRom
.word gSnoruntLevelUpLearnset+SizeRom
.word gGlalieLevelUpLearnset+SizeRom
.word gLunatoneLevelUpLearnset+SizeRom
.word gSolrockLevelUpLearnset+SizeRom
.word gAzurillLevelUpLearnset+SizeRom
.word gSpoinkLevelUpLearnset+SizeRom
.word gGrumpigLevelUpLearnset+SizeRom
.word gPlusleLevelUpLearnset+SizeRom
.word gMinunLevelUpLearnset+SizeRom
.word gMawileLevelUpLearnset+SizeRom
.word gMedititeLevelUpLearnset+SizeRom
.word gMedichamLevelUpLearnset+SizeRom
.word gSwabluLevelUpLearnset+SizeRom
.word gAltariaLevelUpLearnset+SizeRom
.word gWynautLevelUpLearnset+SizeRom
.word gDuskullLevelUpLearnset+SizeRom
.word gDusclopsLevelUpLearnset+SizeRom
.word gRoseliaLevelUpLearnset+SizeRom
.word gSlakothLevelUpLearnset+SizeRom
.word gVigorothLevelUpLearnset+SizeRom
.word gSlakingLevelUpLearnset+SizeRom
.word gGulpinLevelUpLearnset+SizeRom
.word gSwalotLevelUpLearnset+SizeRom
.word gTropiusLevelUpLearnset+SizeRom
.word gWhismurLevelUpLearnset+SizeRom
.word gLoudredLevelUpLearnset+SizeRom
.word gExploudLevelUpLearnset+SizeRom
.word gClamperlLevelUpLearnset+SizeRom
.word gHuntailLevelUpLearnset+SizeRom
.word gGorebyssLevelUpLearnset+SizeRom
.word gAbsolLevelUpLearnset+SizeRom
.word gShuppetLevelUpLearnset+SizeRom
.word gBanetteLevelUpLearnset+SizeRom
.word gSeviperLevelUpLearnset+SizeRom
.word gZangooseLevelUpLearnset+SizeRom
.word gRelicanthLevelUpLearnset+SizeRom
.word gAronLevelUpLearnset+SizeRom
.word gLaironLevelUpLearnset+SizeRom
.word gAggronLevelUpLearnset+SizeRom
.word gCastformLevelUpLearnset+SizeRom
.word gVolbeatLevelUpLearnset+SizeRom
.word gIllumiseLevelUpLearnset+SizeRom
.word gLileepLevelUpLearnset+SizeRom
.word gCradilyLevelUpLearnset+SizeRom
.word gAnorithLevelUpLearnset+SizeRom
.word gArmaldoLevelUpLearnset+SizeRom
.word gRaltsLevelUpLearnset+SizeRom
.word gKirliaLevelUpLearnset+SizeRom
.word gGardevoirLevelUpLearnset+SizeRom
.word gBagonLevelUpLearnset+SizeRom
.word gShelgonLevelUpLearnset+SizeRom
.word gSalamenceLevelUpLearnset+SizeRom
.word gBeldumLevelUpLearnset+SizeRom
.word gMetangLevelUpLearnset+SizeRom
.word gMetagrossLevelUpLearnset+SizeRom
.word gRegirockLevelUpLearnset+SizeRom
.word gRegiceLevelUpLearnset+SizeRom
.word gRegisteelLevelUpLearnset+SizeRom
.word gKyogreLevelUpLearnset+SizeRom
.word gGroudonLevelUpLearnset+SizeRom
.word gRayquazaLevelUpLearnset+SizeRom
.word gLatiasLevelUpLearnset+SizeRom
.word gLatiosLevelUpLearnset+SizeRom
.word gJirachiLevelUpLearnset+SizeRom
.word gDeoxysLevelUpLearnset+SizeRom
.word gChimechoLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gUnownLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
.word gBulbasaurLevelUpLearnset+SizeRom
